name: Auto-py-to-exe

on:
  workflow_run:
      workflows:
        - 'Pylint'
      types:
        - completed
      branches:
        - main
jobs:
  build:
    strategy:
     matrix:
      python-version: ["3.10"]
    runs-on: windows-latest

    steps:

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install auto-py-to-exe --no-input

      - name: Build .exe file
        run: |
          pyinstaller --noconfirm --onefile --console  "stats.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stats.exe
          path: dist\stats.exe

  publish:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: stats.exe

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.run_number }}
          name: ${{ github.run_number }}
          files: ${{ steps.download.outputs.download-path }}\stats.exe